name: Build APK
on: [push]  # Trigger the workflow on every code push

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux machine in the cloud
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pull your code from GitHub

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # Make Gradle executable

      - name: Build APK
        run: ./gradlew assembleDebug  # Build the APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk  # Name of the APK artifact
          path: app/build/outputs/apk/debug/app-debug.apk  # Path to the APK
